<template>
  <div class="k-modal">
    <Loading v-if="loading" />

    <div class="modal-content" v-else>
      <div class="section section-header">
        <p class="no-margin-top size-medium">{{ selectSelectedJob.name }}</p>
        <h1 class="job-name ellipsis">{{ selectSelectedJob.address }}</h1>
      </div>
      <div class="section section-middle">
        <div class="flex-row">
          <div class="flex-column">
            <dl>
              <dt>Job Added</dt>
              <dd>{{ selectSelectedJob.jobAdded }}</dd>
              <dt>Liquidity Manager Balance</dt>
              <dd>{{ selectSelectedJob.liquidityManagerBalance }} {{ selectSelectedLiquidity.symbol }}</dd>
              <dt>Current Bonds <a underline @click="openJobUnbondModal">(unbond)</a></dt>
              <dd>{{ selectSelectedJob.currentBonds }} {{ selectSelectedLiquidity.symbol }}</dd>
            </dl>
          </div>
          <div class="flex-column">
            <dl>
              <dt>Total Credits</dt>
              <dd>{{ selectSelectedJob.credits }}</dd>
              <dt>User Balance</dt>
              <dd>{{ selectSelectedJob.userBalance }} {{ selectSelectedLiquidity.symbol }}</dd>
              <dt>Refill Schedule (X credits in Y hours)</dt>

              <dd v-if="isRefillNA(selectSelectedJob.creditsRefillAt)">N/A</dd>
              <dd v-else>{{ selectSelectedJob.userBalance }} / {{ refillsIn(selectSelectedJob.creditsRefillAt) }}</dd>
            </dl>
          </div>
        </div>
      </div>
      <div class="section section-text">
        <div class="flex-row">
          <div class="flex-column">
            <p class="size-medium"><strong>1. Deposit to liquidity manager</strong></p>
            <p>
              Jobs need credits to be able to pay keepers. These credits can be generated by providing liquidity in the
              system. If you are a liquidity provider you get all your liquidity back after you are done being a
              provider.
            </p>

            <p>
              As a first step, you have to call <i>depositLiquidity(address,uint)</i> to move your liquidity to
              liquidity manager. <strong>Note</strong>, 2.5% fee is charged to cover liquidity manager auto-provision.
            </p>
            <div class="flex-row flex-small">
              <div class="flex-column flex-end">
                <Dropdown
                  :options="getLiquidityOptions"
                  :selected="selectSelectedLiquidity"
                  @input="handleLiquidityInput"
                  class="select top-items"
                  size="double"
                />
              </div>
              <div class="flex-column">
                <Input
                  :class="{ error: false }"
                  placeholder="0.000000"
                  :maxValue="setDepositMaxValue"
                  @onInput="checkDepositValue"
                />
              </div>
            </div>
            <Button
              theme="fill"
              size="small"
              @onClick="deposit"
              :disabled="!getIsWalletConnected || selectCurrentLiqStatusMap.deposit.loading"
            >
              <Loading v-if="selectCurrentLiqStatusMap.deposit.loading" />
              Deposit
            </Button>
          </div>
          <div class="flex-column flex-content">
            <div>
              <p class="size-medium"><strong>2. Set liquidity and apply credits</strong></p>
              <p>
                As a second step, you have to call <i>setJobLiquidityAmount(address,address,uint)</i> to add liquidity
                to the job. From now on, your job will always have credits as your liquidity is rotated automatically.
                Remember, there is a 3-day bonding delay until your first batch of credits get minted.
              </p>
            </div>
            <div>
              <div class="flex-row flex-small">
                <div class="flex-column flex-end">
                  <Dropdown
                    :options="getLiquidityOptions"
                    :selected="selectSelectedLiquidity"
                    @input="handleLiquidityInput"
                    class="select top-items"
                    size="double"
                  />
                </div>
                <div class="flex-column">
                  <Input
                    :class="{ error: false }"
                    placeholder="0.000000"
                    :maxValue="setLiquidityMaxValue"
                    @onInput="checkSetValue"
                  />
                </div>
              </div>
              <Button
                theme="fill"
                size="small"
                @onClick="setJobLiquidity"
                :disabled="!getIsWalletConnected || selectCurrentJobLiqStatusMap.set.loading"
              >
                <Loading v-if="selectCurrentJobLiqStatusMap.set.loading" />
                Set Liquidity
              </Button>
            </div>
          </div>
        </div>
      </div>
      <div class="section last">
        <h4>Documentation</h4>
        <p class="more">
          <a href="https://github.com/keep3r-network/keep3r.network" target="_blank">Read more on github</a>
        </p>
      </div>
      <Button @onClick="$emit('close')" theme="close" />
    </div>
  </div>
</template>

<script>
import { mapGetters } from 'vuex';
import { DateTime } from 'luxon';
import BigNumber from 'bignumber.js';
import { humanizeAmount } from '@/shared/utils';

import Button from '@/components/Button';
import Dropdown from '@/components/Dropdown';
import Input from '@/components/Input';
import Loading from '@/components/Loading';

export default {
  name: 'JobBondModal',
  components: { Button, Dropdown, Input, Loading },
  computed: {
    ...mapGetters('jobs', [
      'selectGetJobDataStatus',
      'selectGetUserJobDataStatus',
      'selectSelectedJob',
      'selectCurrentJobLiqStatusMap',
    ]),
    ...mapGetters('liquidities', ['selectLiquidities', 'selectSelectedLiquidity', 'selectCurrentLiqStatusMap']),
    ...mapGetters('wallet', ['getIsWalletConnected']),
    getLiquidityOptions() {
      return this.selectLiquidities.map((liquidity) => ({
        ...liquidity,
        value: liquidity.symbol,
        tag: liquidity.protocol,
        // TODO populate with real icons and remove `TODO DUMMY ICONS UNTIL REAL` from dropdown.vue
        // icons: ['url1', 'url2'],
      }));
    },
    loading() {
      return this.selectGetJobDataStatus.loading || this.selectGetUserJobDataStatus.loading;
    },
    setDepositMaxValue() {
      return humanizeAmount(this.selectSelectedJob.userBalanceRaw, undefined, '18');
    },
    setLiquidityMaxValue() {
      return humanizeAmount(
        BigNumber(this.selectSelectedJob.liquidityManagerBalanceRaw).plus(this.selectSelectedJob.currentBondsRaw),
        undefined,
        '18'
      );
    },
  },
  data() {
    return {
      inputDeposit: '0',
      inputSet: '0',
    };
  },
  methods: {
    handleLiquidityInput(liquidity) {
      this.$store.commit('liquidities/SELECT_LIQUIDITY', { liquidityAddress: liquidity.address });
    },
    isRefillNA(timestamp) {
      return Number(timestamp) < Number(DateTime.now().toSeconds());
    },
    refillsIn(timestamp) {
      const t = Number(timestamp);
      return (t ? DateTime.fromSeconds(t).toRelative() : 'N/A') || 'N/A';
    },
    async deposit() {
      const amount = new BigNumber(this.inputDeposit);
      const address = this.selectSelectedLiquidity.address;
      const res = await this.$store.dispatch('liquidities/depositLiquidity', { liqAddress: address, amount });
      if (res) this.inputDeposit = '0';
    },
    async setJobLiquidity() {
      const amount = new BigNumber(this.inputSet);
      const res = await this.$store.dispatch('jobs/setJobLiquidity', {
        jobAddress: this.selectSelectedJob.address,
        liqAddress: this.selectSelectedLiquidity.address,
        amount,
      });
      if (res) this.inputSet = '0';
    },
    checkDepositValue(value) {
      // TODO needed checks
      this.inputDeposit = value;
    },
    checkSetValue(value) {
      // TODO needed checks
      this.inputSet = value;
    },
    openJobUnbondModal() {
      this.$store.dispatch('modals/openModal', { name: 'jobUnbond' });
    },
  },
};
</script>
<style scoped>
.k-modal {
  padding: 3rem 4rem 4rem;
}
.modal-content {
  width: 1120px;
}
.k-modal .section.section-header {
  padding: 0.8rem 0 1rem 0;
}
.section.section-text {
  padding: 1.5em 0 2rem 0;
}
.section.section-text p {
  margin: 1.5rem 0;
}
.no-margin-top.size-medium {
  margin-bottom: 0.7rem;
}
.k-modal .flex-row .flex-column p:first-child {
  margin-top: 0;
}
</style>
